spring.application.name=loanmanagement
server.port=${PORT:8080}

spring.datasource.url=jdbc:mysql://shinkansen.proxy.rlwy.net:16900/railway?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=kxeotKJEqZrsJtAEeFygGpvdwnAQXPTK
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

jwt.secret=mySuperSecretKeyForJWTTokenGeneration123456
jwt.expiration=604800000

JAVA_TOOL_OPTIONS=-Xmx300m -Xms100m